import { ViroMaterials } from "@viro-community/react-viro";

export const objects = [
	{
		id: 0,
		title: "Zebra",
		source: require("../res/zebra/zebra.obj"),
		resources: [require("../res/zebra/zebra.mtl")],
		materials_list: ["zebra1", "zebra2", "zebra3"],
		colors: ["white", "brown", "red"],
		materials: "zebra1",
		type: "OBJ",
		environment: "Safari",
		category: "Mammals",
		imageUri: require("../res/zebra/zebra.png"),
		position: [0, 0, 0],
	},
	{
		id: 1,
		title: "Giraffe",
		source: require("../res/giraffe/giraffe.obj"),
		resources: [require("../res/giraffe/giraffe.mtl")],
		materials_list: ["giraffe1", "giraffe2", "giraffe3"],
		colors: ["white", "yellow", "green"],
		materials: "giraffe1",
		type: "OBJ",
		environment: "Safari",
		category: "Mammals",
		imageUri: require("../res/giraffe/giraffe.png"),
		position: [0, 0, 0],
	},
	{
		id: 2,
		title: "Apple",
		source: require("../res/apple/apple.obj"),
		resources: [require("../res/apple/apple.mtl")],
		materials_list: ["apple1", "apple2", "apple3"],
		colors: ["red", "green", "yellow"],
		materials: "apple1",
		type: "OBJ",
		environment: "Market",
		category: "Fruit",
		imageUri: require("../res/apple/apple.png"),
		position: [0, -0.1, 0],
	},
	{
		id: 3,
		title: "Banana",
		source: require("../res/banana/banana.obj"),
		resources: [require("../res/banana/banana.mtl")],
		materials_list: ["banana1", "banana2", "banana3"],
		colors: ["yellow", "green", "brown"],
		materials: "banana1",
		type: "OBJ",
		environment: "Market",
		category: "Fruit",
		imageUri: require("../res/banana/banana.png"),
		position: [0, 0, 0],
	},
	{
		id: 4,
		title: "Carrot",
		source: require("../res/carrot/carrot.obj"),
		resources: [require("../res/carrot/carrot.mtl")],
		materials_list: ["carrot1", "carrot2", "carrot3"],
		colors: ["orange", "white", "brown"],
		materials: "carrot1",
		type: "OBJ",
		environment: "Market",
		category: "Vegetables",
		imageUri: require("../res/carrot/carrot.png"),
		position: [0, 0, 0],
	},
	{
		id: 5,
		title: "Cucumber",
		source: require("../res/cucumber/cucumber.obj"),
		resources: [require("../res/cucumber/cucumber.mtl")],
		materials_list: ["cucumber1", "cucumber2", "cucumber3"],
		colors: ["green", "cyan", "black"],
		materials: "cucumber1",
		type: "OBJ",
		environment: "Market",
		category: "Vegetables",
		imageUri: require("../res/cucumber/cucumber.png"),
		position: [0, 0, 0],
	},
	{
		id: 6,
		title: "Dragonfruit",
		source: require("../res/dragonfruit/dragonfruit.obj"),
		resources: [require("../res/dragonfruit/dragonfruit.mtl")],
		materials_list: ["dragonfruit1", "dragonfruit2", "dragonfruit3"],
		colors: ["pink", "yellow", "black"],
		materials: "dragonfruit1",
		type: "OBJ",
		environment: "Market",
		category: "Exotic",
		imageUri: require("../res/dragonfruit/dragonfruit.png"),
		position: [0, 0, 0],
	},
	{
		id: 7,
		title: "Eggplant",
		source: require("../res/eggplant/eggplant.obj"),
		resources: [require("../res/eggplant/Eggplant.mtl")],
		materials_list: ["eggplant1", "eggplant2", "eggplant3"],
		colors: ["purple", "white", "yellow"],
		materials: "eggplant1",
		type: "OBJ",
		environment: "Market",
		category: "Vegetables",
		imageUri: require("../res/eggplant/eggplant.png"),
		position: [0, 0, 0],
	},
	{
		id: 8,
		title: "Peach",
		source: require("../res/peach/peach.obj"),
		resources: [require("../res/peach/peach.mtl")],
		materials_list: ["peach1", "peach2", "peach3"],
		colors: ["orange", "purple", "black"],
		materials: "peach1",
		type: "OBJ",
		environment: "Market",
		category: "Fruit",
		imageUri: require("../res/peach/peach.png"),
		position: [0, 0, 0],
	},
	{
		id: 9,
		title: "Chimpanzees",
		source: require("../res/chimpanzees/chimpanzees.obj"),
		resources: [require("../res/chimpanzees/chimpanzees.mtl")],
		materials_list: ["chimpanzees1", "chimpanzees2", "chimpanzees3"],
		colors: ["blue", "black", "brown"],
		materials: "chimpanzees1",
		type: "OBJ",
		environment: "Safari",
		category: "Mammals",
		imageUri: require("../res/chimpanzees/chimpanzees.png"),
		position: [0, 0, 0],
	},
	{
		id: 10,
		title: "Pufferfish",
		source: require("../res/pufferfish/pufferfish.obj"),
		resources: [require("../res/pufferfish/pufferfish.mtl")],
		materials_list: ["pufferfish1", "pufferfish2", "pufferfish3"],
		colors: ["brown", "blue", "red"],
		materials: "pufferfish1",
		type: "OBJ",
		environment: "Safari",
		category: "Fishes",
		imageUri: require("../res/pufferfish/pufferfish.png"),
		position: [0, 0, 0],
	},
	{
		id: 11,
		title: "Goldfish",
		source: require("../res/goldfish/goldfish.obj"),
		resources: [require("../res/goldfish/goldfish.mtl")],
		materials_list: ["goldfish1", "goldfish2", "goldfish3"],
		colors: ["orange", "cyan", "brown"],
		materials: "goldfish1",
		type: "OBJ",
		environment: "Safari",
		category: "Fishes",
		imageUri: require("../res/goldfish/goldfish.png"),
		position: [0, 0, 0],
	},
	{
		id: 12,
		title: "Egg",
		source: require("../res/egg/egg.obj"),
		resources: [require("../res/egg/egg.mtl")],
		materials_list: ["egg1", "egg2", "egg3"],
		colors: ["orange", "white", "blue"],
		materials: "egg1",
		type: "OBJ",
		environment: "Kitchen",
		category: "Fridge",
		imageUri: require("../res/egg/egg.png"),
		position: [0, 0, 0],
	},
	{
		id: 13,
		title: "Milk",
		source: require("../res/milk/milk.obj"),
		resources: [require("../res/milk/milk.mtl")],
		materials_list: ["milk1", "milk2", "milk3"],
		colors: ["white", "orange", "pink"],
		materials: "milk1",
		type: "OBJ",
		environment: "Kitchen",
		category: "Fridge",
		imageUri: require("../res/milk/milk.png"),
		position: [0, 0, 0],
	},
	{
		id: 14,
		title: "Krapfen",
		source: require("../res/krapfen/krapfen.obj"),
		resources: [require("../res/krapfen/krapfen.mtl")],
		materials_list: ["krapfen1", "krapfen2", "krapfen3"],
		colors: ["orange", "cyan", "pink"],
		materials: "krapfen1",
		type: "OBJ",
		environment: "Kitchen",
		category: "Desserts",
		imageUri: require("../res/krapfen/krapfen.png"),
		position: [0, 0, 0],
	},
	{
		id: 15,
		title: "Cake",
		source: require("../res/cake/cake.obj"),
		resources: [require("../res/cake/cake.mtl")],
		materials_list: ["cake1", "cake2", "cake3"],
		colors: ["orange", "red", "brown"],
		materials: "cake1",
		type: "OBJ",
		environment: "Kitchen",
		category: "Desserts",
		imageUri: require("../res/cake/cake.png"),
		position: [0, 0, 0],
	},
	{
		id: 16,
		title: "Snake",
		source: require("../res/snake/snake.obj"),
		resources: [require("../res/snake/snake.mtl")],
		materials_list: ["snake1", "snake2", "snake3"],
		colors: ["green", "cyan", "orange"],
		materials: "snake1",
		type: "OBJ",
		environment: "Safari",
		category: "Reptiles",
		imageUri: require("../res/snake/snake.png"),
		position: [0, 0, 0],
	},
];

ViroMaterials.createMaterials({
	zebra1: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/zebra/zebra_Base_color1.png"),
		metalnessTexture: require("../res/zebra/zebra_Metallic.png"),
		roughnessTexture: require("../res/zebra/zebra_Roughness.png"),
	},
	zebra2: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/zebra/zebra_Base_color2.png"),
		metalnessTexture: require("../res/zebra/zebra_Metallic.png"),
		roughnessTexture: require("../res/zebra/zebra_Roughness.png"),
	},
	zebra3: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/zebra/zebra_Base_color3.png"),
		metalnessTexture: require("../res/zebra/zebra_Metallic.png"),
		roughnessTexture: require("../res/zebra/zebra_Roughness.png"),
	},
	giraffe1: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/giraffe/giraffe_Base_color1.png"),
		metalnessTexture: require("../res/giraffe/giraffe_Metallic.png"),
		roughnessTexture: require("../res/giraffe/giraffe_Roughness.png"),
	},
	giraffe2: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/giraffe/giraffe_Base_color2.png"),
		metalnessTexture: require("../res/giraffe/giraffe_Metallic.png"),
		roughnessTexture: require("../res/giraffe/giraffe_Roughness.png"),
	},
	giraffe3: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/giraffe/giraffe_Base_color3.png"),
		metalnessTexture: require("../res/giraffe/giraffe_Metallic.png"),
		roughnessTexture: require("../res/giraffe/giraffe_Roughness.png"),
	},
	apple1: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/apple/apple_Base_color1.png"),
		metalnessTexture: require("../res/apple/apple_Metallic.png"),
		roughnessTexture: require("../res/apple/apple_Roughness.png"),
	},
	apple2: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/apple/apple_Base_color2.png"),
		metalnessTexture: require("../res/apple/apple_Metallic.png"),
		roughnessTexture: require("../res/apple/apple_Roughness.png"),
	},
	apple3: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/apple/apple_Base_color3.png"),
		metalnessTexture: require("../res/apple/apple_Metallic.png"),
		roughnessTexture: require("../res/apple/apple_Roughness.png"),
	},
	banana1: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/banana/banana_Base_color1.png"),
		metalnessTexture: require("../res/banana/banana_Metallic.png"),
		roughnessTexture: require("../res/banana/banana_Roughness.png"),
	},
	banana2: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/banana/banana_Base_color2.png"),
		metalnessTexture: require("../res/banana/banana_Metallic.png"),
		roughnessTexture: require("../res/banana/banana_Roughness.png"),
	},
	banana3: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/banana/banana_Base_color3.png"),
		metalnessTexture: require("../res/banana/banana_Metallic.png"),
		roughnessTexture: require("../res/banana/banana_Roughness.png"),
	},
	carrot1: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/carrot/carrot_Base_color1.png"),
		roughnessTexture: require("../res/carrot/carrot_Roughness.png"),
	},
	carrot2: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/carrot/carrot_Base_color2.png"),
		roughnessTexture: require("../res/carrot/carrot_Roughness.png"),
	},
	carrot3: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/carrot/carrot_Base_color3.png"),
		roughnessTexture: require("../res/carrot/carrot_Roughness.png"),
	},
	cucumber1: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/cucumber/cucumber_Base_color1.png"),
		roughnessTexture: require("../res/cucumber/cucumber_Roughness.png"),
	},
	cucumber2: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/cucumber/cucumber_Base_color2.png"),
		roughnessTexture: require("../res/cucumber/cucumber_Roughness.png"),
	},
	cucumber3: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/cucumber/cucumber_Base_color3.png"),
		roughnessTexture: require("../res/cucumber/cucumber_Roughness.png"),
	},
	dragonfruit1: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/dragonfruit/dragonfruit_Base_color1.png"),
		metalnessTexture: require("../res/dragonfruit/dragonfruit_Metallic.png"),
		roughnessTexture: require("../res/dragonfruit/dragonfruit_Roughness.png"),
	},
	dragonfruit2: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/dragonfruit/dragonfruit_Base_color2.png"),
		metalnessTexture: require("../res/dragonfruit/dragonfruit_Metallic.png"),
		roughnessTexture: require("../res/dragonfruit/dragonfruit_Roughness.png"),
	},
	dragonfruit3: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/dragonfruit/dragonfruit_Base_color3.png"),
		metalnessTexture: require("../res/dragonfruit/dragonfruit_Metallic.png"),
		roughnessTexture: require("../res/dragonfruit/dragonfruit_Roughness.png"),
	},
	eggplant1: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/eggplant/eggplant_Base_color1.png"),
		roughnessTexture: require("../res/eggplant/eggplant_Roughness.png"),
	},
	eggplant2: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/eggplant/eggplant_Base_color2.png"),
		roughnessTexture: require("../res/eggplant/eggplant_Roughness.png"),
	},
	eggplant3: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/eggplant/eggplant_Base_color3.png"),
		roughnessTexture: require("../res/eggplant/eggplant_Roughness.png"),
	},
	peach1: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/peach/peach_Base_color1.png"),
		roughnessTexture: require("../res/peach/peach_Roughness.png"),
	},
	peach2: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/peach/peach_Base_color2.png"),
		roughnessTexture: require("../res/peach/peach_Roughness.png"),
	},
	peach3: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/peach/peach_Base_color3.png"),
		roughnessTexture: require("../res/peach/peach_Roughness.png"),
	},
	chimpanzees1: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/chimpanzees/chimpanzees_Base_color1.png"),
		metalnessTexture: require("../res/chimpanzees/chimpanzees_Metallic.png"),
		roughnessTexture: require("../res/chimpanzees/chimpanzees_Roughness.png"),
	},
	chimpanzees2: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/chimpanzees/chimpanzees_Base_color2.png"),
		metalnessTexture: require("../res/chimpanzees/chimpanzees_Metallic.png"),
		roughnessTexture: require("../res/chimpanzees/chimpanzees_Roughness.png"),
	},
	chimpanzees3: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/chimpanzees/chimpanzees_Base_color3.png"),
		metalnessTexture: require("../res/chimpanzees/chimpanzees_Metallic.png"),
		roughnessTexture: require("../res/chimpanzees/chimpanzees_Roughness.png"),
	},
	pufferfish1: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/pufferfish/pufferfish_Base_color1.png"),
		metalnessTexture: require("../res/pufferfish/pufferfish_Metallic.png"),
		roughnessTexture: require("../res/pufferfish/pufferfish_Roughness.png"),
	},
	pufferfish2: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/pufferfish/pufferfish_Base_color2.png"),
		metalnessTexture: require("../res/pufferfish/pufferfish_Metallic.png"),
		roughnessTexture: require("../res/pufferfish/pufferfish_Roughness.png"),
	},
	pufferfish3: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/pufferfish/pufferfish_Base_color3.png"),
		metalnessTexture: require("../res/pufferfish/pufferfish_Metallic.png"),
		roughnessTexture: require("../res/pufferfish/pufferfish_Roughness.png"),
	},
	goldfish1: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/goldfish/goldfish_Base_color1.png"),
		metalnessTexture: require("../res/goldfish/goldfish_Metallic.png"),
		roughnessTexture: require("../res/goldfish/goldfish_Roughness.png"),
	},
	goldfish2: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/goldfish/goldfish_Base_color2.png"),
		metalnessTexture: require("../res/goldfish/goldfish_Metallic.png"),
		roughnessTexture: require("../res/goldfish/goldfish_Roughness.png"),
	},
	goldfish3: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/goldfish/goldfish_Base_color3.png"),
		metalnessTexture: require("../res/goldfish/goldfish_Metallic.png"),
		roughnessTexture: require("../res/goldfish/goldfish_Roughness.png"),
	},
	egg1: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/egg/egg_Base_color1.png"),
		metalnessTexture: require("../res/egg/egg_Metallic.png"),
		roughnessTexture: require("../res/egg/egg_Roughness.png"),
	},
	egg2: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/egg/egg_Base_color2.png"),
		metalnessTexture: require("../res/egg/egg_Metallic.png"),
		roughnessTexture: require("../res/egg/egg_Roughness.png"),
	},
	egg3: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/egg/egg_Base_color3.png"),
		metalnessTexture: require("../res/egg/egg_Metallic.png"),
		roughnessTexture: require("../res/egg/egg_Roughness.png"),
	},
	milk1: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/milk/milk_Base_color1.png"),
		metalnessTexture: require("../res/milk/milk_Metallic.png"),
		roughnessTexture: require("../res/milk/milk_Roughness.png"),
	},
	milk2: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/milk/milk_Base_color2.png"),
		metalnessTexture: require("../res/milk/milk_Metallic.png"),
		roughnessTexture: require("../res/milk/milk_Roughness.png"),
	},
	milk3: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/milk/milk_Base_color3.png"),
		metalnessTexture: require("../res/milk/milk_Metallic.png"),
		roughnessTexture: require("../res/milk/milk_Roughness.png"),
	},
	cake1: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/cake/cake_Base_color1.png"),
		metalnessTexture: require("../res/cake/cake_Metallic.png"),
		roughnessTexture: require("../res/cake/cake_Roughness.png"),
	},
	cake2: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/cake/cake_Base_color2.png"),
		metalnessTexture: require("../res/cake/cake_Metallic.png"),
		roughnessTexture: require("../res/cake/cake_Roughness.png"),
	},
	cake3: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/cake/cake_Base_color3.png"),
		metalnessTexture: require("../res/cake/cake_Metallic.png"),
		roughnessTexture: require("../res/cake/cake_Roughness.png"),
	},
	krapfen1: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/krapfen/krapfen_Base_color1.png"),
		metalnessTexture: require("../res/krapfen/krapfen_Metallic.png"),
		roughnessTexture: require("../res/krapfen/krapfen_Roughness.png"),
	},
	krapfen2: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/krapfen/krapfen_Base_color2.png"),
		metalnessTexture: require("../res/krapfen/krapfen_Metallic.png"),
		roughnessTexture: require("../res/krapfen/krapfen_Roughness.png"),
	},
	krapfen3: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/krapfen/krapfen_Base_color3.png"),
		metalnessTexture: require("../res/krapfen/krapfen_Metallic.png"),
		roughnessTexture: require("../res/krapfen/krapfen_Roughness.png"),
	},
	snake1: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/snake/snake_Base_color1.png"),
		metalnessTexture: require("../res/snake/snake_Metallic.png"),
		roughnessTexture: require("../res/snake/snake_Roughness.png"),
	},
	snake2: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/snake/snake_Base_color2.png"),
		metalnessTexture: require("../res/snake/snake_Metallic.png"),
		roughnessTexture: require("../res/snake/snake_Roughness.png"),
	},
	snake3: {
		lightingModel: "PBR",
		diffuseTexture: require("../res/snake/snake_Base_color3.png"),
		metalnessTexture: require("../res/snake/snake_Metallic.png"),
		roughnessTexture: require("../res/snake/snake_Roughness.png"),
	},
});
